name: kids_ev_controller
description: "remotely operate and monitor an electric car for kids controlled by RaspberryPi from a smartphone"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.5.0-180.3.beta <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  google_maps_flutter: ^2.9.0
  geolocator: ^13.0.1


  cupertino_icons: ^1.0.8
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  http: ^0.13.4
  flutter_dotenv: ^5.1.0

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  assets:
    - assets/
    - .env
